development:
   adapter: mysql
   database: rails_blog
   username: meysam
   password: mamrez
   host: localhost
   pool: 5
   encoding: utf8

test:
   adapter: mysql
   database: rails_blog
   username: meysam
   password: mamrez
   host: localhost
   pool: 5
   encoding: utf8

production:
   adapter: mysql
   database: rails_blog
   username: meysam
   password: mamrez
   host: localhost
   pool: 5
   encoding: utf8